### ISSUE TITLE
http://play.bash.academy/ doesn't exist yet?

### ISSUE THREAD

**Issue by omgmog** [lhunath/bash.academy#1]
Hey, thanks for such a nice site! The link to http://play.bash.academy/ seems to not be working currently though..

**Comment by lhunath** [comment]
Yes, Play is theoretical at this point :-)  An interactive learning experience, so to speak.  At the very least, I will need to have something set up that can provide a sandboxed / emulated interactive bash experience in the browser.

**Comment by r00tn3p4l** [comment]
C'mon it's 2017

**Comment by lhunath** [comment]
You're welcome to contribute a pull request.
