### ISSUE TITLE
Text overflow in one of the examples. Pincture included.

### ISSUE THREAD

**Issue by ar-qun** [lhunath/bash.academy#4]
![screenshot_20160305_135125](https://cloud.githubusercontent.com/assets/17101722/13547590/6d3d107e-e2d9-11e5-8980-3ed609a1d69d.png)

http://guide.bash.academy/02.commands.html#toc10

Search for "you have wo"

Happens in firefox and chromium.

**Comment by edouard-lopez** [comment]
**Can't reproduce.**

### `Firefox 45.0b10`

![selection_001](https://cloud.githubusercontent.com/assets/1212392/13566914/554b4d2a-e458-11e5-885c-9d10bf6f396b.png)

### Chromium `48.0.2564.116`

![selection_002](https://cloud.githubusercontent.com/assets/1212392/13566942/60d143b6-e458-11e5-8901-901113b4faba.png)

### OS

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

**Comment by jjatria** [comment]
Same here: no problem in Chromium on Kubuntu.

**Comment by lhunath** [comment]
This issue was fixed, just forgot to close :-)
