### ISSUE TITLE
Underlined commands hide underscores

### ISSUE THREAD

**Issue by jjatria** [lhunath/bash.academy#6]
![underline_hides_underscores](https://cloud.githubusercontent.com/assets/2975989/13571848/33377828-e46f-11e5-98f8-bfa40f863fbe.png)

Commands are underlined because they are clickable, to make selection easier. However, the underline hides underscores, which are often important for examples to work. In quiz examples this is worse, since the commands only appear when hovered upon, so it's almost impossible to see them without the underline.

Maybe we don't need the underline, or it can be made fainter, or moved lower?

**Comment by lhunath** [comment]
fixed in 67e74a7
